export default {

getList(){
  
  return [
    {cap:" Cortex",name:"CTXC",val:"USDT",text:"ctxcusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Wanchain",name:"WAN",val:"USDT",text:"wanusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" COCOS BCX",name:"COCOS",val:"USDT",text:"cocosusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Trust Wallet Token",name:"TWT",val:"USDT",text:"twtusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/5964.png"},
    {cap:" AC Milan Fan Token",name:"ACM",val:"USDT",text:"acmusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" NKN",name:"NKN",val:"USDT",text:"nknusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Atletico Madrid Fan Token",name:"ATM",val:"USDT",text:"atmusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Drep",name:"DREP",val:"USDT",text:"drepusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/3924.png"},
    {cap:" GXChain",name:"GXS",val:"USDT",text:"gxsusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" AS Roma Fan Token",name:"ASR",val:"USDT",text:"asrusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" sUSD",name:"SUSD",val:"USDT",text:"susdusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" TokenClub",name:"TCT",val:"USDT",text:"tctusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" FIO Protocol",name:"FIO",val:"USDT",text:"fiousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Paris Saint-Germain Fan Token",name:"PSG",val:"USDT",text:"psgusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Measurable Data Token",name:"MDT",val:"USDT",text:"mdtusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Troy",name:"TROY",val:"USDT",text:"troyusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" RSK Infrastructure Framework",name:"RIF",val:"USDT",text:"rifusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Dock",name:"DOCK",val:"USDT",text:"dockusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Juventus Fan Token",name:"JUV",val:"USDT",text:"juvusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" OG Fan Token",name:"OG",val:"USDT",text:"ogusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Vite",name:"VITE",val:"USDT",text:"viteusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Firo",name:"FIRO",val:"USDT",text:"firousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Audius",name:"AUDIO",val:"USDT",text:"audiousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Mithril",name:"MITH",val:"USDT",text:"mithusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Travala.com",name:"AVA",val:"USDT",text:"avausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Gifto",name:"GTO",val:"USDT",text:"gtousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Metal",name:"MTL",val:"USDT",text:"mtlusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Wrapped NXM",name:"WNXM",val:"USDT",text:"wnxmusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Streamr DATAcoin",name:"DATA",val:"USDT",text:"datausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" ARPA Chain",name:"ARPA",val:"USDT",text:"arpausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" FunFair",name:"FUN",val:"USDT",text:"funusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Hive",name:"HIVE",val:"USDT",text:"hiveusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Nuls",name:"NULS",val:"USDT",text:"nulsusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" LTO Network",name:"LTO",val:"USDT",text:"ltousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Wing Finance",name:"WING",val:"USDT",text:"wingusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" BEAM",name:"BEAM",val:"USDT",text:"beamusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Augur",name:"REP",val:"USDT",text:"repusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" New BitShares",name:"NBS",val:"USDT",text:"nbsusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Stratis",name:"STRAX",val:"USDT",text:"straxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Chromia",name:"CHR",val:"USDT",text:"chrusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Ardor",name:"ARDR",val:"USDT",text:"ardrusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" MovieBloc",name:"MBL",val:"USDT",text:"mblusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Contentos",name:"COS",val:"USDT",text:"cosusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" UTRUST",name:"UTK",val:"USDT",text:"utkusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Nervos Network",name:"CKB",val:"USDT",text:"ckbusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Helium",name:"HNT",val:"USDT",text:"hntusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" TrueFi",name:"TRU",val:"USDT",text:"truusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Perlin",name:"PERL",val:"USDT",text:"perlusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" STP Network",name:"STPT",val:"USDT",text:"stptusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Waltonchain",name:"WTC",val:"USDT",text:"wtcusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Decred",name:"DCR",val:"USDT",text:"dcrusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Celo",name:"CELO",val:"USDT",text:"celousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Komodo",name:"KMD",val:"USDT",text:"kmdusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Numeraire",name:"NMR",val:"USDT",text:"nmrusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Aragon",name:"ANT",val:"USDT",text:"antusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" IRISnet",name:"IRIS",val:"USDT",text:"irisusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" BitShares",name:"BTS",val:"USDT",text:"btsusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" district0x",name:"DNT",val:"USDT",text:"dntusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" DUSK Network",name:"DUSK",val:"USDT",text:"duskusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" WINk",name:"WIN",val:"USDT",text:"winusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" UMA",name:"UMA",val:"USDT",text:"umausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" WazirX",name:"WRX",val:"USDT",text:"wrxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" IoTeX",name:"IOTX",val:"USDT",text:"iotxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Origin Protocol",name:"OGN",val:"USDT",text:"ognusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/5117.png"},
    {cap:" StormX",name:"STMX",val:"USDT",text:"stmxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Axie Infinity",name:"AXS",val:"USDT",text:"axsusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Cartesi",name:"CTSI",val:"USDT",text:"ctsiusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Orchid Protocol",name:"OXT",val:"USDT",text:"oxtusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" VeThor Token",name:"VTHO",val:"USDT",text:"vthousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Akropolis",name:"AKRO",val:"USDT",text:"akrousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Lisk",name:"LSK",val:"USDT",text:"lskusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" CertiK",name:"CTK",val:"USDT",text:"ctkusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Celer Network",name:"CELR",val:"USDT",text:"celrusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" iExec RLC",name:"RLC",val:"USDT",text:"rlcusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Storj",name:"STORJ",val:"USDT",text:"storjusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Kyber Network",name:"KNC",val:"USDT",text:"kncusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" SKALE",name:"SKL",val:"USDT",text:"sklusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Aion",name:"AION",val:"USDT",text:"aionusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" DIA",name:"DIA",val:"USDT",text:"diausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Bella Protocol",name:"BEL",val:"USDT",text:"belusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" PAX Gold",name:"PAXG",val:"USDT",text:"paxgusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Harmony",name:"ONE",val:"USDT",text:"oneusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Decentraland",name:"MANA",val:"USDT",text:"manausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" SelfKey",name:"KEY",val:"USDT",text:"keyusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" DigiByte",name:"DGB",val:"USDT",text:"dgbusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" pNetwork",name:"PNT",val:"USDT",text:"pntusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" HARD Protocol",name:"HARD",val:"USDT",text:"hardusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" JUST",name:"JST",val:"USDT",text:"jstusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Balancer",name:"BAL",val:"USDT",text:"balusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Siacoin",name:"SC",val:"USDT",text:"scusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Maker",name:"MKR",val:"USDT",text:"mkrusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Oasis Network",name:"ROSE",val:"USDT",text:"roseusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Civic",name:"CVC",val:"USDT",text:"cvcusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Loopring",name:"LRC",val:"USDT",text:"lrcusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" bZx Protocol",name:"BZRX",val:"USDT",text:"bzrxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Hifi Finance",name:"MFT",val:"USDT",text:"mftusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" TrueUSD",name:"TUSD",val:"USDT",text:"tusdusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Tellor",name:"TRB",val:"USDT",text:"trbusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Flamingo Finance",name:"FLM",val:"USDT",text:"flmusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Fetch.ai",name:"FET",val:"USDT",text:"fetusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Injective Protocol",name:"INJ",val:"USDT",text:"injusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Nano",name:"NANO",val:"USDT",text:"nanousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Enjin Coin",name:"ENJ",val:"USDT",text:"enjusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Theta Fuel",name:"TFUEL",val:"USDT",text:"tfuelusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Bluzelle",name:"BLZ",val:"USDT",text:"blzusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Unifi Protocol DAO",name:"UNFI",val:"USDT",text:"unfiusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Paxos Standard",name:"PAX",val:"USDT",text:"paxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Ontology Gas",name:"ONG",val:"USDT",text:"ongusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" SAND",name:"SAND",val:"USDT",text:"sandusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Bancor Network Token",name:"BNT",val:"USDT",text:"bntusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Near",name:"NEAR",val:"USDT",text:"nearusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Horizen",name:"ZEN",val:"USDT",text:"zenusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" COTI",name:"COTI",val:"USDT",text:"cotiusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Ocean Protocol",name:"OCEAN",val:"USDT",text:"oceanusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" DFI.money",name:"YFII",val:"USDT",text:"yfiiusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Ankr",name:"ANKR",val:"USDT",text:"ankrusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Compound",name:"COMP",val:"USDT",text:"compusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Reserve Rights Token",name:"RSR",val:"USDT",text:"rsrusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Waves",name:"WAVES",val:"USDT",text:"wavesusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Kava.io",name:"KAVA",val:"USDT",text:"kavausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Hedera Hashgraph",name:"HBAR",val:"USDT",text:"hbarusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" FTX Token",name:"FTT",val:"USDT",text:"fttusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Dent",name:"DENT",val:"USDT",text:"dentusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Qtum",name:"QTUM",val:"USDT",text:"qtumusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Orion Protocol",name:"ORN",val:"USDT",text:"ornusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Sun Token",name:"SUN",val:"USDT",text:"sunusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Alpha Finance",name:"ALPHA",val:"USDT",text:"alphausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Basic Attention Token",name:"BAT",val:"USDT",text:"batusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" OMG Network",name:"OMG",val:"USDT",text:"omgusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Synthetix Network Token",name:"SNX",val:"USDT",text:"snxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Stacks",name:"STX",val:"USDT",text:"stxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" SafePal",name:"SFP",val:"USDT",text:"sfpusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Litentry",name:"LIT",val:"USDT",text:"litusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/6833.png"},
    {cap:" Tezos",name:"XTZ",val:"USDT",text:"xtzusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Zilliqa",name:"ZIL",val:"USDT",text:"zilusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/2469.png"},
    {cap:" Curve DAO Token",name:"CRV",val:"USDT",text:"crvusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Monero",name:"XMR",val:"USDT",text:"xmrusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" 0x",name:"ZRX",val:"USDT",text:"zrxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Kusama",name:"KSM",val:"USDT",text:"ksmusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Theta Network",name:"THETA",val:"USDT",text:"thetausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" DODO",name:"DODO",val:"USDT",text:"dodousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" REN",name:"REN",val:"USDT",text:"renusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" THORChain",name:"RUNE",val:"USDT",text:"runeusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Holo",name:"HOT",val:"USDT",text:"hotusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" BitTorrent",name:"BTT",val:"USDT",text:"bttusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" ICON",name:"ICX",val:"USDT",text:"icxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Pundi X",name:"NPXS",val:"USDT",text:"npxsusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Band Protocol",name:"BAND",val:"USDT",text:"bandusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" 1inch",name:"1INCH",val:"USDT",text:"1inchusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/8104.png"},
    {cap:" yearn.finance",name:"YFI",val:"USDT",text:"yfiusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Zcash",name:"ZEC",val:"USDT",text:"zecusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" IOTA",name:"IOTA",val:"USDT",text:"iotausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Ethereum Classic",name:"ETC",val:"USDT",text:"etcusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Chiliz",name:"CHZ",val:"USDT",text:"chzusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Algorand",name:"ALGO",val:"USDT",text:"algousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Elrond",name:"EGLD",val:"USDT",text:"egldusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" TomoChain",name:"TOMO",val:"USDT",text:"tomousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Venus",name:"XVS",val:"USDT",text:"xvsusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Filecoin",name:"FIL",val:"USDT",text:"filusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Reef Finance",name:"REEF",val:"USDT",text:"reefusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Sushi",name:"SUSHI",val:"USDT",text:"sushiusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Avalanche",name:"AVAX",val:"USDT",text:"avaxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png"},
    {cap:" Ontology",name:"ONT",val:"USDT",text:"ontusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Dash",name:"DASH",val:"USDT",text:"dashusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Ravencoin",name:"RVN",val:"USDT",text:"rvnusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" NEO",name:"NEO",val:"USDT",text:"neousdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" NEM",name:"XEM",val:"USDT",text:"xemusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Polygon",name:"MATIC",val:"USDT",text:"maticusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" PancakeSwap",name:"CAKE",val:"USDT",text:"cakeusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Terra",name:"LUNA",val:"USDT",text:"lunausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" VeChain",name:"VET",val:"USDT",text:"vetusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Stellar",name:"XLM",val:"USDT",text:"xlmusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" TRON",name:"TRX",val:"USDT",text:"trxusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Cosmos",name:"ATOM",val:"USDT",text:"atomusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" The Graph",name:"GRT",val:"USDT",text:"grtusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" BTC Standard Hashrate Token",name:"BTCST",val:"USDT",text:"btcstusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Aave",name:"AAVE",val:"USDT",text:"aaveusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Serum",name:"SRM",val:"USDT",text:"srmusdt",price:"-",color:"",pic:"https://assets.coingecko.com/coins/images/11970/thumb/serum-logo.png?1597121577"},
    {cap:" Swipe",name:"SXP",val:"USDT",text:"sxpusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" EOS",name:"EOS",val:"USDT",text:"eosusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Solana",name:"SOL",val:"USDT",text:"solusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Bitcoin Cash",name:"BCH",val:"USDT",text:"bchusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Uniswap",name:"UNI",val:"USDT",text:"uniusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" IOST",name:"IOST",val:"USDT",text:"iostusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Fantom",name:"FTM",val:"USDT",text:"ftmusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" USD Coin",name:"USDC",val:"USDT",text:"usdcusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Chainlink",name:"LINK",val:"USDT",text:"linkusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Dogecoin",name:"DOGE",val:"USDT",text:"dogeusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Litecoin",name:"LTC",val:"USDT",text:"ltcusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" XRP",name:"XRP",val:"USDT",text:"xrpusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Polkadot",name:"DOT",val:"USDT",text:"dotusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Cardano",name:"ADA",val:"USDT",text:"adausdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Binance USD",name:"BUSD",val:"USDT",text:"busdusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Ethereum",name:"ETH",val:"USDT",text:"ethusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},
    {cap:" Binance Coin",name:"BNB",val:"USDT",text:"bnbusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png"},
    {cap:" Bitcoin",name:"BTC",val:"USDT",text:"btcusdt",price:"-",color:"",pic:"https://s2.coinmarketcap.com/static/img/coins/64x64/1.png"},

  ]
}

};